# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d71b72e1276556911da76d3933c3ce65080d527b5905749e7cfbba75f18982db0c788ac65daee8a094e22d27d385b21ae4b3907b76bf5621468726dda2e926be

test:
  secret_key_base: eae6bcdac084c2d616b8d7344b35d9aa3d7a3e6369be2a4843a7f0bdc44fef620d7658da7ec4bec1b1a36f17262afb7b52b2a9bb15d832193469da273c95b417

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
